### ISSUE TITLE
The Intercept-Only Model

### ISSUE THREAD

**Issue by ewestrich** [learn-co-curriculum/dsc-regression-model-evaluation#1]
I believe the paragraph explaining this graph is incorrect:

<img src="images/linreg_rsq.png" width="600">

We will determine this answer in terms of both statistical significance and goodness-of-fit by comparing the the ***errors*** made by our model (gray vertical arrow) to the errors made by the intercept-only model (orange vertical arrow) and determining the difference between them (red vertical arrow).

The error made by the model is the "red" arrow and the "gray" arrow is the difference between model error and intercept-only model error.

**Comment by christine-egan42** [comment]
fixed with commit #f8632b1
